acct.web/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using acct.common.POCO;
using acct.service;
using acct.common.Repository;
using acct.web.Helper;
using AutoMapper;
using System.Configuration;
using PagedList;

namespace acct.web.Controllers
{
    [Authorize]
    public class ExpenseController : Controller
    {
        //
        // GET: /Expense/

        ExpenseSvc svc;
        ExpenseCategorySvc expenseCategorySvc = new ExpenseCategorySvc();
        ControllerHelper cHelper;
        public ExpenseController(IExpenseRepo iExpenseRepo)
        {
            svc = new ExpenseSvc(iExpenseRepo);
            cHelper = new ControllerHelper(this, iExpenseRepo);
        }
        public ActionResult Index(int? page)
        {
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);
            int _page = page == null ? 1 : (int)page;

            IPagedList<Expense> list = svc.GetAll()
                .OrderBy(x => x.Date)
                .ToPagedList(_page, pageSize);

            return View(list);

        }

        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(expenseCategorySvc.GetAll(), "Id", "Category");

            Expense _Expense = new Expense();
            _Expense.Date = DateTime.Today;
            return View(_Expense);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(Expense Expense, FormCollection collection)
        {
            if (ModelState.IsValid)
            {

                this.UpdateModel(Expense);


                svc.Save(Expense);

                return RedirectToAction("Details", new { id = Expense.Id });
            }
            ViewBag.CategoryId = new SelectList(expenseCategorySvc.GetAll(), "Id", "Category");
            return View(Expense);
        }

        public ActionResult Edit(int id)
        {
            Expense _entity = svc.GetById(id);
            ViewBag.CategoryId = new SelectList(expenseCategorySvc.GetAll(), "Id", "Category", _entity.CategoryId);
            return View(_entity);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit(int id, Expense Expense, FormCollection collection)
        {
            Expense _entity = svc.GetById(id);
            if (ModelState.IsValid)
            {
                _entity.Date = Convert.ToDateTime(collection["Date"]);
                _entity.Amount = Convert.ToDecimal(collection["Amount"]);
                _entity.Remark = collection["Remark"];
                _entity.CategoryId = int.Parse(collection["CategoryId"]);
                try
                {
                    svc.Update(_entity);
                }
                catch (Exception e)
                {

                }


                return RedirectToAction("Details", new { id = _entity.Id });
            }
            ViewBag.CategoryId = new SelectList(expenseCategorySvc.GetAll(), "Id", "Category", _entity.CategoryId);
            return View(_entity);
        }

        public ActionResult Details(int id)
        {
            Expense _entity = svc.GetById(id);
            ViewBag.CategoryId = new SelectList(expenseCategorySvc.GetAll(), "Id", "Category", _entity.CategoryId);
            return View(_entity);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete(int id)
        {
            try
            {
                string succ = "1 record Deleted";
                svc.Delete(id);
                return Json(new { status = true, message = succ });
            }
            catch (Exception e)
            {
                return Json(new { status = false, message = "error when delete" });
            }
            //}

        }
        public ActionResult Print()
        {
            IList<Expense> list = svc.GetAll().Take(10).ToList();

            Mapper.AssertConfigurationIsValid();
            List<Expense> reportList = new List<Expense>();
            foreach (var item in list)
            {
                Expense cust =
                    Mapper.Map<Expense, Expense>(item);
                reportList.Add(cust);
            }

            string ReportFile = "~/Content/reports/order/Expenses.rdlc";
            string DataSourceName = "DataSet_Expenses";


            Byte[] bytes = cHelper.GetReport(ReportFile, DataSourceName, reportList);

            string fileName = "Expenses.pdf";
            return File(bytes, "application/pdf", fileName);
        }

    }
}

acct.web/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using acct.common.POCO;
using acct.service;
using acct.web.Helper;
using acct.common.Repository;
using System.Configuration;
using PagedList;
using acct.service.Helper;
using AutoMapper;
using acct.common.Helper;
namespace acct.web.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        //
        // GET: /Invoice/
        InvoiceSvc svc = new InvoiceSvc();
        GSTSvc gstSvc = new GSTSvc();
        OptionsSvc optionsSvc = new OptionsSvc();
        CustomerSvc customerSvc;
        SalesmanSvc salesmanSvc;
        OrderSvc orderSvc = new OrderSvc();
        ControllerHelper cHelper;
        public InvoiceController(ICustomerRepo iCustomerRepo, ISalesmanRepo iSalesmanRepo)
        {
            cHelper = new ControllerHelper(this, iCustomerRepo);
            customerSvc = new CustomerSvc(iCustomerRepo);
            salesmanSvc = new SalesmanSvc(iSalesmanRepo);
        }
        public ActionResult Index(int? page, int? dateRange, List<string> status)
        {
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);
            int _page = page == null ? 1 : (int)page;
            DateRange.DateRangeFilter drFilter = dateRange == null ? DateRange.DateRangeFilter.AnyTime : (DateRange.DateRangeFilter)dateRange;

            List<Order.StatusOptions> statusList = new List<Order.StatusOptions>();
            if (status != null)
            {
                foreach (var item in status)
                {
                    Order.StatusOptions _status =
                    (Order.StatusOptions)Enum.Parse(typeof(Order.StatusOptions), item);
                    statusList.Add(_status);
                }
            }
            else
            {
                statusList.Add(Order.StatusOptions.Unpaid);
            }
            IPagedList<Invoice> onePageOfProducts = svc.GetByFilter(statusList, null, drFilter)
                .ToPagedList(_page, pageSize);

            return View(onePageOfProducts);
        }
        public ActionResult Search(string q, int? page)
        {
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);
            int _page = page == null ? 1 : (int)page;

            if (string.IsNullOrEmpty(q)) { return RedirectToAction("Index"); }
            IPagedList<Invoice> list = svc.GetAll().Where
                (o => o.OrderNumber.Contains(q))
                .ToList()
                .ToPagedList(_page, pageSize);

            ViewBag.q = q;

            return View("Index", list);
        }
        [Route("Invoice/Customer/{id}")]
        public ActionResult GetByCustomer(int id, int? page)
        {
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);
            int _page = page == null ? 1 : (int)page;

            Customer customer = customerSvc.GetById(id);
            if (customer != null)
            {
                IPagedList<Invoice> list = svc.GetByCustomer(id)
                .ToPagedList(_page, pageSize);
                return View("Index", list);
            }
            return View("Index");
            
        }

        //home/about
        public ActionResult GetTopInvoices(int id, int count)
        {

            Salesman salesman = salesmanSvc.GetById(id);
            if (salesman != null)
            {
                IList<Invoice> list = svc.GetAll()
                    .Where(i => i.SalesmanId == id)
                    .OrderByDescending(i => i.OrderDate)
                    .Take(count)
                    .ToList();
                return View("Index", list);
            }
            return View("Index");

        }

        public ActionResult GetMonthlyTotal(DateTime year)
        {
            //var data=svc.GetMonthlyTotal(year);
            //IList<Invoice> list=svc.GetAll().Where(i => i.Order.OrderDate > year).ToList();

            //Error: LINQ to Entities does not recognize the method 'System.String Format(System.String, System.Object, System.Object)' method, and this method cannot be translated into a store expression.
            //var summary = from s in svc.GetAll().Where(i => i.Order.OrderDate > year)
            //              group s by new { month = s.Order.OrderDate.Month, year = s.Order.OrderDate.Year } into g
            //              orderby g.Key.year,g.Key.month
            //              select new
            //              {
            //                  month = string.Format("{0}/{1}", g.Key.month, g.Key.year),
            //                  total = g.Sum(x => x.Order.TotalAmount)
            //              };

            //Perfomance Issue
            //var summary = from s in list
            //              let k = new
            //              {
            //                  month = s.Order.OrderDate.ToString("yy/MM")
            //              }
            //              group s by k into g
            //              orderby g.Key.month
            //              select new
            //              {
            //                  month = g.Key.month,
            //                  total = g.Sum(x => x.Order.TotalAmount)
            //              };

            //var query = myList.GroupBy(i => i.DateTimeField.HasValue ? i.DateTimeField.Value.Month : 0)
            //      .Select(g => new
            //      {
            //          Month = g.Key,
            //          Total = g.Sum(i => i.AmountField)
            //      });

            var summary = from s in svc.GetAll().Where(i => i.OrderDate > year)
                          group s by new { month = s.OrderDate.Month, year = s.OrderDate.Year } into g
                          orderby g.Key.year, g.Key.month
                          select new
                          {
                              year = g.Key.year,
                              month = g.Key.month ,
                              total = g.Sum(x => x.TotalAmount)
                          };

            var json=from s in summary.ToList()
                     select new {
                         month = new DateTime(s.year, s.month, 1).ToString("MMM-yy", System.Globalization.CultureInfo.InvariantCulture),
                         total=s.total
                     };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetYearlyTopCustomer(DateTime year)
        {
            var summary = from s in svc.GetAll().Where(i => i.OrderDate > year)
                          group s by new { customer = s.Customer.Name } into g
                          orderby g.Key.customer
                          select new
                          {
                              customer = g.Key.customer,
                              total = g.Sum(x => x.TotalAmount)
                          };

            var json = from s in summary.OrderByDescending(s=>s.total).Take(10).ToList()
                       select new
                       {
                           customer = s.customer.TruncateLongString(20),
                           total = Decimal.Round(s.total,0)
                       };

            decimal others_total = 0;
            if (summary.OrderByDescending(s => s.total).Skip(10).Any())
            {
                others_total = summary.OrderByDescending(s => s.total).Skip(10).Sum(s => s.total);
            }

            var others = new[]
            {
                new 
                {
                    customer = "Others",
                    total = Decimal.Round(others_total,0)
                }
            };

            json=json.Concat(others);

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetYearlyTopSalesman(DateTime year)
        {
            var summary = from s in svc.GetAll().Where(i => i.OrderDate > year)
                          group s by new { salesman = s.Salesman.Name } into g
                          orderby g.Key.salesman
                          select new
                          {
                              salesman = g.Key.salesman,
                              total = g.Sum(x => x.TotalAmount)
                          };

            var json = from s in summary.OrderByDescending(s => s.total).Take(10).ToList()
                       select new
                       {
                           salesman = s.salesman.TruncateLongString(20),
                           total = Decimal.Round(s.total, 0)
                       };

            decimal others_total = 0;
            if(summary.OrderByDescending(s => s.total).Skip(10).Any()){
                others_total=summary.OrderByDescending(s => s.total).Skip(10).Sum(s => s.total);
            }
            


            var others = new[]
            {
                new 
                {
                    salesman = "Others",
                    total = Decimal.Round(others_total,0)
                }
            };

            json = json.Concat(others);

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public int GetISOWeek(DateTime day){
            return System.Globalization.CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(day, System.Globalization.CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Sunday);
        }

        public ActionResult Create(int? id)
        {
            Invoice _item = new Invoice();

            ViewBag.idmas_GST = new SelectList(gstSvc.GetAll(), "Id", "Code");
            ViewBag.CustomerId = cHelper.GetCustomerDropDown(id);
            ViewBag.NewDetail = new OrderDetail();

            _item.OrderNumber = optionsSvc.GetNextInvoiceNumber();
            _item.OrderDate = DateTime.Today;

            return View(_item);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(Invoice entity, FormCollection collection)
        {
            

acct.web/Controllers/ToolsController.cs
using acct.common.Repository;
using acct.service.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace acct.web.Controllers
{
    public class ToolsController : Controller
    {
        DataImportor dataImportor;
        public ToolsController(ICustomerRepo iCustomerRepo, IGSTRepo iGSTRepo,
            IInvoiceRepo iInvoiceRepo, IOrderDetailRepo iOrderDetailRepo,
            ISalesmanRepo iSalesmanRepo, IPaymentRepo iPaymentRepo, IPaymentDetailRepo iPaymentDetailRepo)
        {
            dataImportor = new DataImportor(iCustomerRepo, iGSTRepo, iInvoiceRepo,
                iOrderDetailRepo, iSalesmanRepo, iPaymentRepo, iPaymentDetailRepo);
        }
        // GET: Tools
        public ActionResult ImportData()
        {
            return View();
        }
         [HttpPost]
        public ActionResult ImportData(FormCollection collection)
        {
             int counter = 0;
             int errors = 0;
             foreach (string upload in Request.Files)
             {
                 HttpPostedFileBase file = Request.Files[upload];
                 if (file.ContentLength > 0)
                 {
                     try
                     {
                         if (upload == "FileUploadSalesman")
                         {
                             counter = dataImportor.ImportSalesman(file.InputStream);
                         }
                         if (upload == "FileUploadCustomer")
                         {
                             counter = dataImportor.ImportCustomer(file.InputStream);
                         }
                         else if (upload == "FileUploadInvoiceHeader")
                         {
                             counter = dataImportor.ImportInvioceHeader(file.InputStream);
                         }
                         else if (upload == "FileUploadInvoiceDetail")
                         {
                             counter = dataImportor.ImportInvioceDetail(file.InputStream);
                         }
                         else if (upload == "FileUploadInvoice")
                         {
                             counter = dataImportor.ImportInvioce(file.InputStream);
                         }
                         else if (upload == "FileUploadPaymentHeader")
                         {
                             counter = dataImportor.ImportPaymentHeader(file.InputStream);
                         }
                         else if (upload == "FileUploadPaymentDetail")
                         {
                             counter = dataImportor.ImportPaymentDetail(file.InputStream);
                         }
                     }
                     catch (Exception e)
                     {
                         errors++;
                     }
                     
                     
                 }
             }
            //byte[] uploadedFile = new byte[model.File.InputStream.Length];
            //model.File.InputStream.Read(uploadedFile, 0, uploadedFile.Length);
             ViewData["message"] = counter + " records imported!" + errors + " errors !";
            return View();
        }
    }
}

acct.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @using acct.web.Helper
    <meta charset="utf-8" />
    <title>@ViewBag.Title - ACCT</title>
    <link rel="icon" type="image/x-icon" href="@Url.Content("~/favicon.ico")" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/sitecss")
    @Styles.Render("~/Content/bootstrapcss")
    @*@Styles.Render("~/Content/themes/base/css")*@
    @Scripts.Render("~/bundles/modernizr")
    <!-- include your less or built css files  -->
    <!--
    bootstrap-datetimepicker-build.less will pull in "../bootstrap/variables.less" and "bootstrap-datetimepicker.less";
    or
    <link rel="stylesheet" href="/Content/bootstrap-datetimepicker.css" />
    -->
    
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="logo">
                @*<img src='@Html.ImageUrlFor("~/Images/ThickPotentialLogo.png")' />*@
                <img src='@Html.ImageUrlFor("~/Images/PawleckLogo.png")' />

            </div>
            @if (Request.IsAuthenticated)
            {
                <nav class="navbar " role="navigation">
                    <div class="container-fluid">

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav">

                                <li>
                                    @Html.ActionLink("Dashboard", "Index", "Home", new { Area = "" }, new { })
                                </li>
                                <li>
                                    @Html.ActionLink("Dashboard sales", "About", "Home", new { Area = "" }, new { })
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sales <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Customer ", "Index", "Customer", new { page = "", Area = "" }, null)</li>
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("Quotations ", "Index", "Quotation", new { page = "", Area = "" }, null)</li>
                                        <li>@Html.ActionLink("New Quotation ", "Create", "Quotation", new { page = "", Area = "" }, null)</li>
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("Invoices ", "Index", "Invoice", new { page = "", Area = "" }, null)</li>
                                        <li>@Html.ActionLink("New Invoice ", "Create", "Invoice", new { page = "", Area = "" }, null)</li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Purchasing <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Vendor ", "Index", "Vendor", new { page = "", Area = "" }, null)</li>
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("Purchase Order ", "Index", "Purchase", new { page = "", Area = "" }, null)</li>
                                        <li>@Html.ActionLink("New Purchase Order ", "Create", "Purchase", new { page = "", Area = "" }, null)</li>

                                    </ul>
                                </li>
                                <li>
                                    @Html.ActionLink("Expenses", "Index", "Expense", new { page = "", Area = "" }, null)
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Report <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("4-line statement", "4LineStatement", "Report", new { page = "", Area = "" }, null)</li>
                                    </ul>
                                </li>

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Setup <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("GST", "Index", "GST", new { page = "", Area = "" }, null)</li>
                                        <li>@Html.ActionLink("Salesman", "Index", "Salesman", new { page = "", Area = "" }, null)</li>
                                        <li>@Html.ActionLink("Expense Category", "Index", "ExpenseCategory", new { page = "", Area = "" }, null)</li>
                                        @*<li>@Html.ActionLink("Unit Measure", "Index", "UnitMeasure", new { page = "", Area = "" }, null)</li>*@
                                        <li class="divider"></li>
                                        <li>@Html.ActionLink("Options ", "Index", "Options", new { page = "", Area = "" }, null)</li>
                                        <li>@Html.ActionLink("Import Data", "ImportData", "Tools", new { page = "", Area = "" }, null)</li>

                                    </ul>
                                </li>
                            </ul>

                            <ul class="nav navbar-nav navbar-right">
                                @Html.Partial("_LoginPartial")
                            </ul>
                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                    <!-- /.container-fluid -->
                </nav>
            }
        </div>
        <div class="head">
            <div class="head-titles">
                @ViewBag.Title
            </div>
        </div>
        <div id="main">
           @RenderBody()
        </div>
        <div id="footer">
            &copy; @(DateTime.Today.Year) Thick Potential Technology, All Rights Reserved
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/shared")
    @RenderSection("scripts", required: false)
    
</body>
</html>

acct.web/Views/Shared/_SearchBox.cshtml
<div class="input-group">
    <input type="text" autocomplete="off" class="form-control" placeholder="Search..." name="q" id="q" value="@ViewBag.q">
    <div class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
    </div>
</div>