acct.web/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using acct.common.POCO;
using acct.service;
using acct.common.Repository;
using acct.web.Helper;
using AutoMapper;
using System.Configuration;
using PagedList;

namespace acct.web.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        //
        // GET: /Customer/
        
        CustomerSvc svc;
        GSTSvc gstSvc = new GSTSvc();
        InvoiceSvc invoiceSvc = new InvoiceSvc();
        ControllerHelper cHelper;
        public CustomerController(ICustomerRepo iCustomerRepo)
        {
            svc = new CustomerSvc(iCustomerRepo);
            cHelper = new ControllerHelper(this, iCustomerRepo);
        }
        public ActionResult ngIndex()
        {
            return View();

        }
        public ActionResult ngDetails(int id)
        {
            return View();

        }
        public ActionResult Index(int? page,string q)
        {
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);
            int _page = page == null ? 1 : (int)page;

            var list = svc.GetAll();

            if (!string.IsNullOrEmpty(q)) {
                list = svc.Search(q);
                ViewBag.q = q;
            }

            IPagedList<Customer> pagedList = list.OrderBy(x => x.Name)
                .ToPagedList(_page, pageSize);

            return View(pagedList);

        }
        public ActionResult Lookup(string q, int limit=5)
        {
            IList<Customer> entity = null;
            if (!string.IsNullOrEmpty(q))// && q.Length >= 2)
            {
                entity = svc.GetAll().Where
                    (o => o.Name.Contains(q))
                .ToList();

                if (entity != null)
                {
                    var returnValue = from c in entity
                                    .Take(limit)
                                      orderby c.Name
                                      select new
                                      {
                                          id = c.Id.ToString(),
                                          value = c.Name
                                      };
                    return Json(returnValue, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Create()
        {
            ViewBag.idmas_GST = new SelectList(gstSvc.GetAll(), "Id", "Code");

            Customer _customer = new Customer();
            return View(_customer);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(Customer customer, FormCollection collection)
        {
            if (ModelState.IsValid)
            {

                this.UpdateModel(customer);


                svc.Save(customer);

                return RedirectToAction("Details", new { id = customer.Id });
            }
            ViewBag.idmas_GST = new SelectList(gstSvc.GetAll(), "Id", "Code");
            return View(customer);
        }

        public ActionResult Edit(int id)
        {
            Customer _entity = svc.GetById(id);
            ViewBag.idmas_GST = new SelectList(gstSvc.GetAll(), "Id", "Code", _entity.idmas_GST);
            return View(_entity);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit(int id,Customer customer, FormCollection collection)
        {
            Customer _entity = svc.GetById(id);
            if (ModelState.IsValid)
            {
                _entity.Name = collection["Name"];
                _entity.Address = collection["Address"];
                _entity.Phone = collection["Phone"];
                _entity.Fax = collection["Fax"];
                _entity.Email = string.IsNullOrEmpty(collection["Email"])?null:collection["Email"];
                _entity.ContactName = collection["ContactName"];

                _entity.idmas_GST =int.Parse(collection["idmas_GST"]);
                try
                {
                    svc.Update(_entity);
                }
                catch (Exception e)
                {
                    
                }
                

                return RedirectToAction("Details", new { id = _entity.Id });
            }
            ViewBag.idmas_GST = new SelectList(gstSvc.GetAll(), "Id", "Code", _entity.idmas_GST);
            return View(_entity);
        }

        public ActionResult Details(int id)
        {
            Customer _entity = svc.GetById(id);
            ViewBag.idmas_GST = new SelectList(gstSvc.GetAll(), "Id", "Code", _entity.idmas_GST);

            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);
            int page = 1;
            int _page = page == null ? 1 : (int)page;

            IPagedList<Invoice> list = invoiceSvc.GetByCustomer(id)
                .ToPagedList(_page, pageSize);
            ViewBag.RecentInvoice = list;

            decimal balance=svc.GetBalance(id);
            ViewBag.balance = balance.ToString("C");

            return View(_entity);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete(int id)
        {
            try
            {
                string succ = "1 record Deleted";
                svc.Delete(id);
                return Json(new { status = true, message = succ });
            }
            catch (Exception e)
            {
                return Json(new { status = false, message = "error when delete" });
            }
            //}

        }
        public ActionResult Print()
        {
            IList <Customer> list = svc.GetAll().Take(10).ToList();

            Mapper.AssertConfigurationIsValid();
            List<Customer> reportList = new List<Customer>();
            foreach (var item in list)
            {
                Customer cust =
                    Mapper.Map<Customer, Customer>(item);
                reportList.Add(cust);
            }

            string ReportFile = "~/Content/reports/order/Customers.rdlc";
            string DataSourceName = "DataSet_Customers";


            Byte[] bytes = cHelper.GetReport(ReportFile, DataSourceName, reportList);

            string fileName = "Customers.pdf";
            return File(bytes, "application/pdf", fileName);
        }

    }
}

acct.web/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using acct.common.POCO;
using acct.service;
using acct.web.Helper;
using acct.common.Repository;
using System.Configuration;
using PagedList;
using acct.service.Helper;
using AutoMapper;
using acct.common.Helper;
namespace acct.web.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        //
        // GET: /Invoice/
        InvoiceSvc svc = new InvoiceSvc();
        GSTSvc gstSvc = new GSTSvc();
        OptionsSvc optionsSvc = new OptionsSvc();
        CustomerSvc customerSvc;
        SalesmanSvc salesmanSvc;
        OrderSvc orderSvc = new OrderSvc();
        ControllerHelper cHelper;
        public InvoiceController(ICustomerRepo iCustomerRepo, ISalesmanRepo iSalesmanRepo)
        {
            cHelper = new ControllerHelper(this, iCustomerRepo);
            customerSvc = new CustomerSvc(iCustomerRepo);
            salesmanSvc = new SalesmanSvc(iSalesmanRepo);
        }
        public ActionResult Index(int? page, int? dateRange, List<string> status)
        {
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);
            int _page = page == null ? 1 : (int)page;
            DateRange.DateRangeFilter drFilter = dateRange == null ? DateRange.DateRangeFilter.AnyTime : (DateRange.DateRangeFilter)dateRange;

            List<Order.StatusOptions> statusList = new List<Order.StatusOptions>();
            if (status != null)
            {
                foreach (var item in status)
                {
                    Order.StatusOptions _status =
                    (Order.StatusOptions)Enum.Parse(typeof(Order.StatusOptions), item);
                    statusList.Add(_status);
                }
            }
            else
            {
                statusList.Add(Order.StatusOptions.Unpaid);
            }
            IPagedList<Invoice> onePageOfProducts = svc.GetByFilter(statusList, null, drFilter)
                .ToPagedList(_page, pageSize);

            return View(onePageOfProducts);
        }
        public ActionResult Search(string q, int? page)
        {
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);
            int _page = page == null ? 1 : (int)page;

            if (string.IsNullOrEmpty(q)) { return RedirectToAction("Index"); }
            IPagedList<Invoice> list = svc.GetAll().Where
                (o => o.OrderNumber.Contains(q))
                .ToList()
                .ToPagedList(_page, pageSize);

            ViewBag.q = q;

            return View("Index", list);
        }
        [Route("Invoice/Customer/{id}")]
        public ActionResult GetByCustomer(int id, int? page)
        {
            int pageSize = int.Parse(ConfigurationManager.AppSettings["pageSize"]);
            int _page = page == null ? 1 : (int)page;

            Customer customer = customerSvc.GetById(id);
            if (customer != null)
            {
                IPagedList<Invoice> list = svc.GetByCustomer(id)
                .ToPagedList(_page, pageSize);
                return View("Index", list);
            }
            return View("Index");
            
        }

        //home/about
        public ActionResult GetTopInvoices(int id, int count)
        {

            Salesman salesman = salesmanSvc.GetById(id);
            if (salesman != null)
            {
                IList<Invoice> list = svc.GetAll()
                    .Where(i => i.SalesmanId == id)
                    .OrderByDescending(i => i.OrderDate)
                    .Take(count)
                    .ToList();
                return View("Index", list);
            }
            return View("Index");

        }

        public ActionResult GetMonthlyTotal(DateTime year)
        {
            //var data=svc.GetMonthlyTotal(year);
            //IList<Invoice> list=svc.GetAll().Where(i => i.Order.OrderDate > year).ToList();

            //Error: LINQ to Entities does not recognize the method 'System.String Format(System.String, System.Object, System.Object)' method, and this method cannot be translated into a store expression.
            //var summary = from s in svc.GetAll().Where(i => i.Order.OrderDate > year)
            //              group s by new { month = s.Order.OrderDate.Month, year = s.Order.OrderDate.Year } into g
            //              orderby g.Key.year,g.Key.month
            //              select new
            //              {
            //                  month = string.Format("{0}/{1}", g.Key.month, g.Key.year),
            //                  total = g.Sum(x => x.Order.TotalAmount)
            //              };

            //Perfomance Issue
            //var summary = from s in list
            //              let k = new
            //              {
            //                  month = s.Order.OrderDate.ToString("yy/MM")
            //              }
            //              group s by k into g
            //              orderby g.Key.month
            //              select new
            //              {
            //                  month = g.Key.month,
            //                  total = g.Sum(x => x.Order.TotalAmount)
            //              };

            //var query = myList.GroupBy(i => i.DateTimeField.HasValue ? i.DateTimeField.Value.Month : 0)
            //      .Select(g => new
            //      {
            //          Month = g.Key,
            //          Total = g.Sum(i => i.AmountField)
            //      });

            var summary = from s in svc.GetAll().Where(i => i.OrderDate > year)
                          group s by new { month = s.OrderDate.Month, year = s.OrderDate.Year } into g
                          orderby g.Key.year, g.Key.month
                          select new
                          {
                              year = g.Key.year,
                              month = g.Key.month ,
                              total = g.Sum(x => x.TotalAmount)
                          };

            var json=from s in summary.ToList()
                     select new {
                         month = new DateTime(s.year, s.month, 1).ToString("MMM-yy", System.Globalization.CultureInfo.InvariantCulture),
                         total=s.total
                     };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetYearlyTopCustomer(DateTime year)
        {
            var summary = from s in svc.GetAll().Where(i => i.OrderDate > year)
                          group s by new { customer = s.Customer.Name } into g
                          orderby g.Key.customer
                          select new
                          {
                              customer = g.Key.customer,
                              total = g.Sum(x => x.TotalAmount)
                          };

            var json = from s in summary.OrderByDescending(s=>s.total).Take(10).ToList()
                       select new
                       {
                           customer = s.customer.TruncateLongString(20),
                           total = Decimal.Round(s.total,0)
                       };

            decimal others_total = 0;
            if (summary.OrderByDescending(s => s.total).Skip(10).Any())
            {
                others_total = summary.OrderByDescending(s => s.total).Skip(10).Sum(s => s.total);
            }

            var others = new[]
            {
                new 
                {
                    customer = "Others",
                    total = Decimal.Round(others_total,0)
                }
            };

            json=json.Concat(others);

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetYearlyTopSalesman(DateTime year)
        {
            var summary = from s in svc.GetAll().Where(i => i.OrderDate > year)
                          group s by new { salesman = s.Salesman.Name } into g
                          orderby g.Key.salesman
                          select new
                          {
                              salesman = g.Key.salesman,
                              total = g.Sum(x => x.TotalAmount)
                          };

            var json = from s in summary.OrderByDescending(s => s.total).Take(10).ToList()
                       select new
                       {
                           salesman = s.salesman.TruncateLongString(20),
                           total = Decimal.Round(s.total, 0)
                       };

            decimal others_total = 0;
            if(summary.OrderByDescending(s => s.total).Skip(10).Any()){
                others_total=summary.OrderByDescending(s => s.total).Skip(10).Sum(s => s.total);
            }
            


            var others = new[]
            {
                new 
                {
                    salesman = "Others",
                    total = Decimal.Round(others_total,0)
                }
            };

            json = json.Concat(others);

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public int GetISOWeek(DateTime day){
            return System.Globalization.CultureInfo.CurrentCulture.Calendar.GetWeekOfYear(day, System.Globalization.CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Sunday);
        }

        public ActionResult Create(int? id)
        {
            Invoice _item = new Invoice();

            ViewBag.idmas_GST = new SelectList(gstSvc.GetAll(), "Id", "Code");
            ViewBag.CustomerId = cHelper.GetCustomerDropDown(id);
            ViewBag.NewDetail = new OrderDetail();

            _item.OrderNumber = optionsSvc.GetNextInvoiceNumber();
            _item.OrderDate = DateTime.Today;

            return View(_item);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(Invoice entity, FormCollection collection)
        {
            

acct.web/Views/Customer/Create.cshtml
@model acct.common.POCO.Customer

@{
    ViewBag.Title = "Create Customer";
    
}
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    Html.RenderPartial("~/Views/Customer/_Form.cshtml", Model);
    <div class="detailview">
        <div class="row">
            <div class="display-label">
				@Html.LabelFor(model => model.idmas_GST)
			</div>
        <div class="display-field">
                @Html.DropDownList("idmas_GST", (SelectList)ViewBag.idmas_GST, new { @class = "form-control" })
				@*@Html.EditorFor(model => model.idmas_GST)*@
				@Html.ValidationMessageFor(model => model.idmas_GST)
			</div>
		</div>
       
       <div class="action-links">
            <input  type="submit" class="button" value="Save" />
            <a class="button" href='@Url.Action("Index", "Customer")'>Back to List</a>
        </div>
    </div>
}

acct.web/Views/Customer/Details.cshtml
@model acct.common.POCO.Customer
@using acct.web.Helper
@{
    ViewBag.Title = @Html.DisplayFor(model => model.Name);

}
<div class="navbar navbar-inner block-header">
    Balance: @ViewBag.balance
    <div class="pull-right">
        <a class="btn btn-primary" href=@Url.Action("Create", "Invoice", new { id = Model.Id }) role="button"><i class="fa fa-plus"></i> New Invoice</a>
        <a class="btn btn-primary" href=@Url.Action("Create", "Quotation", new { id = Model.Id }) role="button"><i class="fa fa-plus"></i> New Quotation</a>
    </div>
</div>

<ul class="nav nav-tabs" role="tablist" id="myTab">
    <li role="presentation"><a href="#sales" role="tab" data-toggle="tab">Transactions</a></li>
    <li role="presentation"><a href="#customer" role="tab" data-toggle="tab">Customer Info</a></li>
</ul>
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="sales">
        <div class="row">
            <div class="col-md-12">
                <h4>@*Monthly Sales*@</h4>
                <div id="transactiondiv">
                    @Html.Partial("~/Views/Invoice/_List.cshtml", (PagedList.PagedList<acct.common.POCO.Invoice>)ViewBag.RecentInvoice)
                </div>
            </div>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="customer">
        <div class="row margin-top30">
            <div class="col-md-12">
                <div class="detailview">
                    @*<div class="row">
                            <div class="display-label">
                                 @Html.DisplayNameFor(model => model.Name)
                            </div>
                            <div class="display-field">
                                @Html.DisplayFor(model => model.Name)
                            </div>
                        </div>*@
                    <div class="row">
                        <div class="display-label">
                            @Html.DisplayNameFor(model => model.Address)
                        </div>
                        <div class="display-field">
                            <address>
                                @Html.FormatBody(Model.Address)
                            </address>
                        </div>
                    </div>
                    <div class="row">
                        <div class="display-label">
                            @Html.DisplayNameFor(model => model.Phone)
                        </div>
                        <div class="display-field">
                            @Html.DisplayFor(model => model.Phone)
                        </div>
                    </div>
                    <div class="row">
                        <div class="display-label">
                            @Html.DisplayNameFor(model => model.Fax)
                        </div>
                        <div class="display-field">
                            @Html.DisplayFor(model => model.Fax)
                        </div>
                    </div>
                    <div class="row">
                        <div class="display-label">
                            @Html.DisplayNameFor(model => model.Email)
                        </div>
                        <div class="display-field">
                            @Html.DisplayFor(model => model.Email)
                        </div>
                    </div>
                    <div class="row">
                        <div class="display-label">
                            @Html.DisplayNameFor(model => model.ContactName)
                        </div>
                        <div class="display-field">
                            @Html.DisplayFor(model => model.ContactName)
                        </div>
                    </div>

                    <div class="row">
                        <div class="display-label">
                            @Html.LabelFor(model => model.idmas_GST)
                        </div>
                        <div class="display-field">
                            @Html.DisplayFor(model => model.GST.Rate)
                        </div>
                    </div>
                </div>
                <div class="action-links">
                    <a class="button" href='@Url.Action("Edit", "Customer",new { id=Model.Id })'> Edit </a>
                    @*<a class="button" href='@Url.Action("Index", "Customer")'>Back to List</a>
                                        <a class="button" href='@Url.Action("Create", "Invoice")'>Add Invoice</a>
                        <a class="button" href='@Url.Action("Customer", "Invoice", new { id = Model.Id })'>Recent Invoices</a>*@
                </div>
            </div>
        </div>
    </div>

</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            $('#myTab a:first').tab('show');
        })
    </script>
}

acct.web/Views/Customer/Edit.cshtml
@model acct.common.POCO.Customer

@{
    ViewBag.Title = "Edit Customer";
    
}
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    Html.RenderPartial("~/Views/Customer/_Form.cshtml", Model);
    <div class="detailview">
        <div class="row">
            <div class="editor-label">
                @Html.LabelFor(model => model.idmas_GST)
            </div>
        <div class="display-field">
                @Html.DropDownList("idmas_GST", (SelectList)ViewBag.idmas_GST, new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.idmas_GST)
			</div>
		</div>
            <div class="action-links">
                <input type="submit" class="button" value="Save" />
                <a class="button"  href='@Url.Action("Index", "Customer")'>Back to List</a>
            </div>
    </div>
}

acct.web/Views/Customer/Index.cshtml
@model IPagedList<acct.common.POCO.Customer>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Customers";
    
}
@using (Html.BeginForm("Index", "Customer", FormMethod.Get, new { id = "searchForm", @class = "form-horizontal", role = "form" }))
{
    Html.RenderPartial("~/Views/Shared/_SearchBox.cshtml");
}
<div class="navbar navbar-inner block-header margin-top30">

    <div class="pull-right">
        <a class="btn btn-primary" href=@Url.Action("Create", "Customer") role="button"><i class="fa fa-plus"></i> New</a>
    </div>
</div>
<table class="table table-hover margin-top15">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Phone)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.First().ContactName)
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr id='row@(item.Id)'>
            <td>
                @Html.ActionLink(item.Name, "Details", new { id = item.Id })
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.ContactName)
            </td>
            <td>
                <a href='@Url.Action("Edit", "Customer", new { id = item.Id })' title="Edit"><i class="glyphicon glyphicon-pencil"></i></a>
                @*<a href='#' id='@item.Id' data-url="Customer" hreflang="delete_href">Delete</a>*@
            </td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page, q = ViewBag.q }))
@section scripts{
    @Scripts.Render("~/bundles/typeahead")
    <script type="text/javascript">
        $(function () {
            initTypeahead('../../Customer/lookup?q=%QUERY');
        });
    </script>
}

acct.web/Views/Customer/ngDetails.cshtml
@*@using acct.web.Helper*@
@{
    ViewBag.Title = "ng detail";

}
<div id="bodyContainer" ng-app="acctApp">
    <div ng-controller="customerDetailController">
        <div class="navbar navbar-inner block-header">
            @*Balance: @ViewBag.balance*@
            <div class="pull-right">
                <a class="btn btn-primary" ng-href='/Invoice/Create/{{customer.Id}}' role="button"><i class="fa fa-plus"></i> New Invoice</a>
                <a class="btn btn-primary" ng-href='/Quotation/Create/{{customer.Id}}' role="button"><i class="fa fa-plus"></i> New Quotation</a>
            </div>
        </div>

        <ul class="nav nav-tabs" role="tablist" id="myTab">
            <li role="presentation"><a href="#sales" role="tab" data-toggle="tab">Transactions</a></li>
            <li role="presentation"><a href="#customer" role="tab" data-toggle="tab">Customer Info</a></li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="sales">
                <div class="row">
                    <div class="col-md-12">
                        <h4>@*Monthly Sales*@</h4>
                        <div id="transactiondiv">
                            @*@Html.Partial("~/Views/Invoice/_List.cshtml", (PagedList.PagedList<acct.common.POCO.Invoice>)ViewBag.RecentInvoice)*@
                        </div>
                    </div>
                </div>
            </div>

            <div role="tabpanel" class="tab-pane" id="customer">
                <div class="row margin-top30">
                    <div class="col-md-12">
                        <div class="detailview">
                            <div class="row">
                                <div class="display-label">
                                    Address
                                </div>
                                <div class="display-field">
                                    <address>
                                        {{customer.Address}}
                                    </address>
                                </div>
                            </div>
                            <div class="row">
                                <div class="display-label">
                                    Phone
                                </div>
                                <div class="display-field">
                                    {{customer.Phone}}
                                </div>
                            </div>
                            <div class="row">
                                <div class="display-label">
                                    Fax
                                </div>
                                <div class="display-field">
                                    {{customer.Fax}}
                                </div>
                            </div>
                            <div class="row">
                                <div class="display-label">
                                    Email
                                </div>
                                <div class="display-field">
                                    {{customer.Email}}
                                </div>
                            </div>
                            <div class="row">
                                <div class="display-label">
                                    Contact Name
                                </div>
                                <div class="display-field">
                                    {{customer.ContactName}}
                                </div>
                            </div>

                            <div class="row">
                                <div class="display-label">
                                    GST
                                </div>
                                <div class="display-field">
                                    {{customer.GST.Rate}}
                                </div>
                            </div>
                        </div>
                        <div class="action-links">
                            <a class="button"  ng-href='/Customer/Edit/{{customer.Id}}' title="Edit">Edit</a>
                            @*<a class="button" href='@Url.Action("Edit", "Customer",new { id=Model.Id })'> Edit </a>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            $('#myTab a:first').tab('show');
        })
    </script>

    @Scripts.Render("~/Scripts/angular.js")
    @Scripts.Render("~/Scripts/angular-resource.js")
    @Scripts.Render("~/Scripts/app/services/customer-servcie.js")
    @Scripts.Render("~/Scripts/app/app.js")
    @Scripts.Render("~/Scripts/app/controllers/customer-controller.js")
}